#!/usr/bin/env bash

author="${3:-David Josephs}"
project_name="${2}"
secret='false'

print_usage(){
	declare -a help=(
	"./create -[s] PROJECT NAME AUTHOR "	)

	printf "%s\n" "${help[@]}" # this is horrible

}

while getopts 's' flag ; do
	case "${flag}" in
		s) secret='true' ;;
		*) print_usage
			exit 1 ;;
	esac
done

if [ "$secret" = "true" ]; then
	echo "$project_name"/ >> .gitignore
fi


bash src/mk_config.sh "$author"  "$project_name"
