#!/usr/bin/env bash

author="${2:-David Josephs}"
project_name="${1}"
secret='false'

print_usage(){
	declare -a help=(
	"./create PROJECT NAME AUTHOR -[s]"	)

	printf "%s\n" "${help[@]}" # this is horrible

}

while getopts 's' flag ; do
	case "${flag}" in
		s) secret='true' ;;
		*) print_usage
			exit 1 ;;
	esac
done


bash src/mk_config.sh "$author" "$secret" "$project_name"
